
name: Rust

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Install xmllint
      run: sudo apt-get install libxcb-composite0-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --examples --tests --features serde_support
    - name: Run tests
      run: cargo test --verbose
      
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --examples --tests --features serde_support
    - name: Run tests
      run: cargo test   
